import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'
import * as data from "../env.json";
import Modal from '../components/Modal'
import { useState } from "react";

type taskType = {
  _id: string,
  task: string,
  completed: boolean,
}

const Home: NextPage = () => {
  const [editTask, setEditTask] = useState<taskType>({} as taskType);
  const [tasks, setTasks] = useState([]);
  const [editModal, setEditModal] = useState<boolean>(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Card editTask={editTask} setEditTask={setEditTask} tasks={tasks} setTasks={setTasks} editModal={editModal} setEditModal={setEditModal}/>
        <Modal editTask={editTask} setEditTask={setEditTask} setTasks={setTasks} editModal={editModal} setEditModal={setEditModal}/>
      </main>
    </div>
  )
}

export default Home
